channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas
  - numpy=1.19.5
  - pip
  - cython
  - libblas
  - libcblas
  - liblapack
  - libcxx
  - libffi
  - libgfortran
  - libgfortran5
  - libopenblas
  - llvm-openmp
  - ncurses
  - numexpr